#!/bin/bash


# cases
#1. just pull repo for first time


git_setup()
{
	echo "Switching to MMSBGHA github for this repo..."
	
	echo "Switched git username to MMSBGHA for this repo"
	git config user.name "MMSBGHA"
	echo "Switched git email to MMSBPMA@protonmail.com for this repo"
	git config user.email MMSBPMA@protonmail.com
	git config credential.helper store
	git push https://github.com/MMSBGHA/ModdedServerBackup.git
	echo ""
}

backup_interval()
{
	300
}

echo "Minecraft Server Autobackup to Github"
printf "%0.s-" {1..35}
printf "\n\n"

# check for git setup
echo "Checking for git setup..."
if [[ $(git config user.name) != "MMSBGHA" ]]
then
	echo "GIT REPO ALREADY SETUP"
else
	echo "GIT REPO NOT SETUP"
	git_setup	
fi

echo git config user.name
echo
echo "STARTING BACKUP..."
printf "%0.s-" {1..35}
echo

echo "Waiting to backup..."
while true
do
	echo "Backing up the server..."
	# add any changes
	git add *
	# make new changes a commit and current time and date as commit message
	git commit -m date 2> nul
	git push origin master 2> nul
	echo "Server backed up."
	sleep 300
done
echo "Backing up ended."